#!/bin/bash

if [[ $# != 1  ]]; then
    echo "il faut utiliser un argument"
    exit 1
fi

n=$1
if [[ $n > 20 ]]; then
    echo "$n est trop grand"
    exit 1
fi
fact=1

# cas de  n = 0
if [[ $n == 0 ]]; then
    echo 1
    exit 0
fi

for ((i=1; i<=n; i++))
do
    fact=$((fact * i))
done

echo "$fact"
