#!/bin/bash
if [[ $# != 1 ]]; then
    echo "il faut avoir un argument"
    exit 1
fi

if(($1 < 0)); then
echo "le nombre doit etre positif"
exit 1
fi

fact() {
    if (($1 == 0)); then
        echo 1
    else
        echo $(( $(fact $(( $1 - 1 ))) * $1 ))
    fi
}

fact "$1"

