#!/bin/bash
if [[ $# != 1 ]]; then
    echo "il faut avoir un argument"
    exit 1
fi

fact() {
    if [[ $1 -le 1 ]]; then
        echo 1
    else
        echo $(( $(fact $(( $1 - 1 ))) * $1 ))
    fi
}

fact "$1"

