#!/bin/bash

fact() {
    if [[ $1 -le 1 ]]; then
        echo 1
    else
        echo $(( $(fact $(( $1 - 1 ))) * $1 ))
    fi
}

# Vérifier argument
if [[ -z "$1" ]]; then
    echo "Usage : $0 N"
    exit 1
fi

fact "$1"

