#!/bin/bash

# Vérifier présence argument
if [[ -z "$1" ]]; then
    echo "Usage : $0 N"
    exit 1
fi

N=$1
fact=1

# Cas N = 0
if [[ $N -eq 0 ]]; then
    echo 1
    exit 0
fi

for ((i=1; i<=N; i++))
do
    fact=$((fact * i))
done

echo "$fact"

#!/bin/bash
