#!/bin/bash
for i 
do 
if [[ -f $i ]]; then
  count=0;
  while read line;dof
    if (( $count < 5 )); then
      echo $line
      ((count++))
    else
      break
    fi
  done < $i
  rm -i $i
else echo "$i pas un fichier ou il n'exist pas"
fi 
done
