#!/bin/bash

if [[ ! -e agenda ]]; then
   touch agenda
fi

while true; do

   echo "1. Ajouter une nouvelle fiche"
   echo "2. Rechercher une fiche (avec une partie du nom)"
   echo "3. Détruire une fiche"
   echo "4. Modifier une fiche"
   echo "5. Lister l’annuaire"
   echo "6. Fin"
   echo -n "votre chois ? : "

   read choix

   case $choix in
      1)
         echo "1. Ajouter une nouvelle fiche"
         echo -n "entrer le nome : "
         read nom
         echo -n "entrer le tele : "
         read tele
         echo "$nom,$tele" >> agenda

         ;;
      2)
         echo "2. Rechercher une fiche (avec une partie du nom): "
         echo -n "enter le nom a rechecher : "
         read nom
         $(cat agenda | grep $nom)
         if [[ $? != 0 ]]; then
            echo "aucune fiche trouvee"
         fi         
         ;;
      3)
         echo "3. Détruire une fiche"
         echo -n "entrer le nom a supprimer : "
         read nom
         grep -v $nom agenda > agenda2
         mv agenda2 agenda
         echo "fiche supprimee"
         ;;
      4) 
         echo "4. Modifier une fiche"
         echo -n "entrer le nom a modifier : "
         read nom
         echo -n "entrer le nouveau tele : "
         read tele
         echo -n "entrer le nouveau nom : "
         read nvnom
         > agenda2
         while IFS=',' read -r old_nom old_tele; do
            if [[ "$old_nom" == "$nom" ]]; then
               echo "$nvnom,$tele" >> agenda2
            else
               echo "$old_nom,$old_tele" >> agenda2
            fi
         done < agenda
         mv agenda2 agenda
         echo "fiche modifiee"
         ;;
      5)
        cat agenda
         ;;
      6)
         echo "fin ..."
         exit 1
         ;;  
      *)
         echo "choix incorrect"
         ;;
   esac
done